In [15]:
import pandas as pd

In [16]:
data = pd.read_csv(r"C:\Users\yueku\Desktop\VScode\Private_nav_research\data\SACG52_千衍六贞1号_2025-12-31.csv")

In [21]:
data.columns = ['date', 'nav_adjusted']

In [22]:
data

           date  nav_adjusted
0    2023-10-23        1.0000
1    2023-10-27        1.0002
2    2023-10-31        1.0004
3    2023-11-03        1.0006
4    2023-11-10        1.0065
..          ...           ...
120  2025-12-05        1.4963
121  2025-12-12        1.5039
122  2025-12-19        1.4795
123  2025-12-26        1.4992
124  2025-12-31        1.4888

[125 rows x 2 columns]

In [26]:
# 中间变量（剔除基准数据）
def intermediate_df(nav_df):
    # 获取基准数据、合并数据
    df = nav_df.copy()
    # 辅助数据
    ## df_nav
    df_nav = df.drop_duplicates(subset=['date'], keep='last').round(4)
    ## df_return
    df["nav_return"] = df["nav_adjusted"].pct_change()
    df["nav_return"] = df["nav_return"].fillna(0)
    df_return = df[["date", "nav_return"]].round(4)
    ## df_drawdown
    df_nav_copy = df_nav.copy()
    df_nav_copy["fun_max_so_far"] = df_nav_copy["nav_adjusted"].cummax()
    df_nav_copy["fund_drawdown"] = (df_nav_copy["nav_adjusted"] - df_nav_copy["fun_max_so_far"]) / df_nav_copy["fun_max_so_far"]
    df_drawdown = df_nav_copy[["date", "fund_drawdown"]].round(4)
    return df_nav, df_return, df_drawdown

In [27]:
df_nav, df_return, df_drawdown = intermediate_df(data)

In [28]:
df_nav

           date  nav_adjusted
0    2023-10-23        1.0000
1    2023-10-27        1.0002
2    2023-10-31        1.0004
3    2023-11-03        1.0006
4    2023-11-10        1.0065
..          ...           ...
120  2025-12-05        1.4963
121  2025-12-12        1.5039
122  2025-12-19        1.4795
123  2025-12-26        1.4992
124  2025-12-31        1.4888

[125 rows x 2 columns]

In [29]:
df_return

           date  nav_return
0    2023-10-23      0.0000
1    2023-10-27      0.0002
2    2023-10-31      0.0002
3    2023-11-03      0.0002
4    2023-11-10      0.0059
..          ...         ...
120  2025-12-05      0.0013
121  2025-12-12      0.0051
122  2025-12-19     -0.0162
123  2025-12-26      0.0133
124  2025-12-31     -0.0069

[125 rows x 2 columns]

In [30]:
df_drawdown

           date  fund_drawdown
0    2023-10-23         0.0000
1    2023-10-27         0.0000
2    2023-10-31         0.0000
3    2023-11-03         0.0000
4    2023-11-10         0.0000
..          ...            ...
120  2025-12-05         0.0000
121  2025-12-12         0.0000
122  2025-12-19        -0.0162
123  2025-12-26        -0.0031
124  2025-12-31        -0.0100

[125 rows x 2 columns]

In [ ]:
import pandas as pd
from pathlib import Path

def rtn_calc(list, end_date="2025-10-31"):
    files_list_series = pd.Series(
        [
            i
            for i in Path("./data").rglob("*")
            if i.suffix.lower() in {".csv", ".xlsx", ".xls"}
        ]
    )
    all_list = []
    for i in list:
        nav_df_path = files_list_series[files_list_series.apply(lambda x: i[1] in x.stem)].values[0]
        nav_df = pd.read_csv(nav_df_path)
        rtn = nav_df[nav_df['日期'] == end_date]['复权净值'].values[0] / nav_df[nav_df['日期'] == i[0]]['复权净值'].values[0] - 1
        all_list.append([i[0],end_date,i[1],i[2],rtn])
    data = pd.DataFrame(all_list,columns=['推荐日期','截止日期','产品代码','产品名称','期间收益率'])
    data['期间收益率'] = data['期间收益率'].apply(lambda x: f"{x:.2%}")
    return data

if __name__ == "__main__":
    recommend_list = [
        ["2025-08-15","SCV067","众壹资产量合兴成一号"],
        ["2025-09-19","SEA420","东海龙王一号"],
        ["2025-09-26","SEM760","草本优益1号"]
    ]
    data = rtn_calc(recommend_list, end_date="2025-10-31")
    print(data)

         推荐日期        截止日期    产品代码        产品名称   期间收益率
0  2025-08-15  2025-10-31  SCV067  众壹资产量合兴成一号  -3.69%
1  2025-09-19  2025-10-31  SEA420      东海龙王一号   2.96%
2  2025-09-26  2025-10-31  SEM760      草本优益1号  -2.76%